# Data
data_dir: "./data/images"
train_class_file: configs/train_class.txt # classes want to train
train_annot: configs/train.txt
test_annot: configs/test.txt

# Model
model_name: vit_b_16
pretrained: true
freeze_backbone: false

# Train configs
seed: 42
batch_size: 16
epochs: 2
summary: False
num_workers: 0

# Change optimizer and its config based on prefix, read docs if necessary
optimizer: adam
learning_rate: 0.1
